### ISSUE TITLE
add caribbean currencies

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/charts#20]

**Comment by islandbitcoin** [comment]
This can prob be closed soon, but there is a duplicated currency XCD in the staging environment 
![Screenshot 2024-04-27 at 11 48 38 AM](https://github.com/lnflash/charts/assets/34528298/6d84ed8d-7002-41c2-b086-9216b9e490e9)

**Comment by brh28** [comment]
@islandbitcoin this is complete correct?

**Comment by islandbitcoin** [comment]
> @islandbitcoin this is complete correct?

No, there is one bug remaining, a duplicate currency that needs to be removed (XCD)

**Comment by brh28** [comment]
Looking at the currency screen, I don't see XCD duplicated. Would you mind confirming it's still an issue? And if so, describe which screen you're seeing it

**Comment by islandbitcoin** [comment]
![Screenshot 2024-07-16 at 12 20 46 PM](https://github.com/user-attachments/assets/2226cf5a-c1ca-4e4b-a635-8a6f315781e1)

**Comment by islandbitcoin** [comment]
looks like its corrected in the main branch, but maybe just not pushed to staging?

https://github.com/lnflash/charts/blob/4d78feee652bde40602ff244cb218967e3d4a324/charts/price/values.yaml#L35-L48

or maybe there is a duplicate in the DB from manual testing that needs to be removed?

**Comment by brh28** [comment]
Seems like this was a deployment issue - we need to make sure we updated the Chart version number when we make changes to config values, otherwise those changes don't get applied

**Comment by islandbitcoin** [comment]
Redeploying fixed the duplication. Noted on updating the chart version.
Closing this issue
